version: "2.2"
services:
  petclinic:
      build:
        context: .
      container_name: my-petclinic
      ports:
        - "8080:8080"
      environment:
        - SPRING_PROFILES_ACTIVE=mysql
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/petclinic
      volumes:
        - ./:/app
      depends_on: ["mysql"]    
  mysql:
      container_name: mysql-petclinic
      image: mysql:5.7.8
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_USER=petclinic
        - MYSQL_PASSWORD=petclinic
        - MYSQL_DATABASE=petclinic
      volumes:
        - "./conf.d:/etc/mysql/conf.d:ro"
      